apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nimue-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "8b7921de-fdf8-4fb1-bdea-720e28e00c0e"
    keyvaultName: "kv-emrys-staging"
    tenantId: "93cf172d-505d-4c23-8ed5-65c508d7a53b"
    objects: |
      array:
        - |
          objectName: nimue-db-user
          objectType: secret
        - |
          objectName: nimue-db-password
          objectType: secret
        - |
          objectName: storage-account-name
          objectType: secret
        - |
          objectName: nimue-blob-sas
          objectType: secret
        - |
          objectName: nimue-telegram-bot-token
          objectType: secret
        - |
          objectName: nimue-telegram-chat-id
          objectType: secret
  secretObjects:
    - secretName: nimue-db-credentials
      type: kubernetes.io/basic-auth
      data:
        - objectName: nimue-db-user
          key: username
        - objectName: nimue-db-password
          key: password
    - secretName: nimue-n8n-env
      type: Opaque
      data:
        - objectName: nimue-db-user
          key: DB_POSTGRESDB_USER
        - objectName: nimue-db-password
          key: DB_POSTGRESDB_PASSWORD
    - secretName: nimue-backup-creds
      type: Opaque
      data:
        - objectName: storage-account-name
          key: storage-account-name
        - objectName: nimue-blob-sas
          key: nimue-blob-sas
    - secretName: nimue-telegram-creds
      type: Opaque
      data:
        - objectName: nimue-telegram-bot-token
          key: TELEGRAM_BOT_TOKEN
        - objectName: nimue-telegram-chat-id
          key: TELEGRAM_CHAT_ID
