apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nimue-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - nimue.staging.emrys.merl.one
      secretName: nimue-tls
  rules:
    - host: nimue.staging.emrys.merl.one
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nimue-n8n
                port:
                  number: 3008
